version: '3.9'

services:
  script_service:
    build: ./
    command: ./wait-for-postgres.sh db ./ScriptService
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nav461
      POSTGRES_DB: Scripts
    hostname: script_service
    container_name: script_service

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nav461
      POSTGRES_DB: Scripts
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.postgres-data:/var/lib/postgresql/data