// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "ScriptService/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// CreateCommand mocks base method.
func (m *MockCommand) CreateCommand(cmd model.Command) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommand", cmd)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCommand indicates an expected call of CreateCommand.
func (mr *MockCommandMockRecorder) CreateCommand(cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommand", reflect.TypeOf((*MockCommand)(nil).CreateCommand), cmd)
}

// DeleteCommand mocks base method.
func (m *MockCommand) DeleteCommand(cmdId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommand", cmdId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCommand indicates an expected call of DeleteCommand.
func (mr *MockCommandMockRecorder) DeleteCommand(cmdId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommand", reflect.TypeOf((*MockCommand)(nil).DeleteCommand), cmdId)
}

// GetAllCommand mocks base method.
func (m *MockCommand) GetAllCommand() ([]model.Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCommand")
	ret0, _ := ret[0].([]model.Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCommand indicates an expected call of GetAllCommand.
func (mr *MockCommandMockRecorder) GetAllCommand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCommand", reflect.TypeOf((*MockCommand)(nil).GetAllCommand))
}

// GetCommand mocks base method.
func (m *MockCommand) GetCommand(cmdId int) (model.Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommand", cmdId)
	ret0, _ := ret[0].(model.Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommand indicates an expected call of GetCommand.
func (mr *MockCommandMockRecorder) GetCommand(cmdId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommand", reflect.TypeOf((*MockCommand)(nil).GetCommand), cmdId)
}

// UpdateCommand mocks base method.
func (m *MockCommand) UpdateCommand(cmdId int, cmdResult string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommand", cmdId, cmdResult)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommand indicates an expected call of UpdateCommand.
func (mr *MockCommandMockRecorder) UpdateCommand(cmdId, cmdResult interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommand", reflect.TypeOf((*MockCommand)(nil).UpdateCommand), cmdId, cmdResult)
}
